export interface NamingContext {
  env: string;
  prefix?: string;
  delimiters: {
    pathSeparator: string;
    afterComponentName: string;
    variantEqualSign: string;
    betweenVariants: string;
  };
  duplicate?: (name: string, count: number) => string;
}

const defaultContext: NamingContext = {
  env: 'css',
  delimiters: {
    pathSeparator: '-',
    afterComponentName: '-',
    variantEqualSign: '_',
    betweenVariants: '-',
  },
  duplicate: (name, count) => `${name}${count}`,
};

export const createNamingConvention = (context: NamingContext = defaultContext) => {
  const nameCountMap = new Map<string, number>();

  return {
    // For grouping instances
    createGroupingKey: (path: Array<{ name: string; type: string }>) => {
      return path
        .filter((part) => part.type !== 'COMPONENT')
        .map(({ name }) => name.replace(/\s+/g, '-'))
        .join('.'); // Use '.' for grouping keys
    },

    // For final naming (your existing logic)
    createName: (path: Array<{ name: string; type: string }>, variantsCombination: string) => {
      // Extract base path using context delimiters
      const basePath =
        path
          ?.filter((part) => part.type !== 'COMPONENT')
          ?.map((part) => part.name.replace(/\s+/g, '-'))
          ?.join(context.delimiters.pathSeparator) || '';

      // Process variants
      const variantParts = variantsCombination.split('--').filter(Boolean);
      /*
       * TODO: ARCHITECTURAL CHANGE NEEDED FOR PROPER CONFLICT DETECTION
       *  Note: This course of resolution for the TODO was generated by AI and may not be optimal, I haven't vetted it yet.
       * CURRENT ISSUE: We can only detect value conflicts within a single variant combination,
       * but we need to detect conflicts across ALL variant combinations for the same component.
       *
       * For example, if we have:
       * - size-default--theme-primary
       * - size-default--theme-default
       * - type-default--theme-primary
       *
       * The value "default" appears in both "size" and "type" properties, so we should use
       * "size_default" and "type_default" to disambiguate, but currently we can't detect this.
       *
       * REQUIRED CHANGES:
       * 1. Modify convertVariantGroupBy to pass ALL variant combinations for a component
       *    to the nameTransform function, not just the current one
       *
       * 2. Change nameTransform signature to:
       *    (path, allVariantCombinations: string[], currentVariantCombination: string) => string
       *
       * 3. Update naming logic to:
       *    a. Build a global value occurrence map across all combinations
       *    b. Track which properties each value appears in
       *    c. Use property_value format only when a value appears in multiple properties
       *    d. Use value-only format when a value is unique to one property
       *
       * 4. This would give us optimal naming:
       *    - button/button.large.primary (when values are unique)
       *    - button/button.size_default.theme_primary (when "default" conflicts)
       *
       * IMPACT: This requires changing the variants-middleware.ts architecture and all
       * transformer functions that use naming conventions.
       *
       * FOR NOW: Using value-only approach for consistency until architectural changes are made.
       *
       */

      const processedVariants = variantParts.map((part) => {
        if (part === 'ROOT') {
          return 'root';
        }

        if (part.includes('-')) {
          const dashIndex = part.indexOf('-');
          const value = part.substring(dashIndex + 1);
          return value.toLowerCase().replace(/\s+/g, '-');
        }

        return part.replace(/\s+/g, '-').toLowerCase();
      });

      let newName = basePath;
      if (processedVariants.length > 0) {
        newName +=
          context.delimiters.afterComponentName +
          processedVariants.join(context.delimiters.betweenVariants);
      }

      // Handle duplicates
      const baseNewName = newName;
      let counter = nameCountMap.get(baseNewName) || 0;
      if (counter > 0) {
        newName = context.duplicate!(baseNewName, counter + 1);
      }
      nameCountMap.set(baseNewName, counter + 1);

      return newName.toLowerCase();
    },
  };
};
